version: "3.9"

services:
  openmemory:
    # Build from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - USER=${USER:-fredchan1709}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://mem0-api.fredchan.dev}
    # Map your app ports
    ports:
      - "8765:8765"
      - "3000:3000"
    # If you want your app to talk to Qdrant by hostname "mem0_store",
    # it will use the default Docker network that Compose creates.
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      USER: ${USER:-fredchan1709}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://mem0-api.fredchan.dev}
    depends_on:
      - mem0_store

  mem0_store:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - mem0_storage:/mem0/storage

volumes:
  mem0_storage: